from ejercicios_funciones import saludar, suma, par_impar, mayoria_edad, conversion, area_tri, mostrar_mayor, letra_palabras, filtrar_pares, es_palindromo, factorial, repetidos, fizzbuzz, vocales, invertir_texto, validar_contraseña, dado, suma_unicos, generar_contraseña, composicion, a_mayusculas, añadir_signos

#saludar()
#suma()
#par_impar()
#mayoria_edad()
#conversion()
#area_tri()
#mostrar_mayor()
#letra_palabras()
#filtrar_pares()
#es_palindromo()
#factorial()
#repetidos()
#fizzbuzz()
#vocales()
#invertir_texto()
#validar_contraseña()
#dado()
#suma_unicos()
#generar_contraseña()
composicion(a_mayusculas, añadir_signos, "python el mejor")